export const homeMapping = {
    acceptAllButton: '[data-testid="uc-accept-all-button"]',
    currencySelector: 'USD$',
    dialogContainer: 'div[role="dialog"]',
    
    // Currency mapping
    currencyMap: {
        'USD': 'US Dollar - $',
        'EUR': 'Euro - €',
        'THB': 'Thai Baht - ฿',
        'GBP': 'Great British Pound - £',
        'JPY': 'Japanese Yen - ¥',
        'CNY': 'Chinese Yuan - CN¥',
        'INR': 'Indian Rupee - Rs',
        'AUD': 'Australian Dollar - AU$',
        'CAD': 'Canadian Dollar - CA$',
        'ZAR': 'South African Rand - R',
        'NZD': 'New Zealand Dollar - NZ$',
        'SGD': 'Singapore Dollar - S$',
        'CHF': 'Swiss Franc - CHF',
        'MYR': 'Malaysian Ringgit - RM',
        'HUF': 'Hungarian Forint - Ft',
        'HKD': 'Hong Kong Dollar - HK$',
        'AED': 'United Arab Emirates Dirham - AED',
        'SEK': 'Swedish Krona - Skr',
        'PHP': 'Philippine Peso - ₱',
        'ILS': 'Israeli New Shekel - ₪',
        'TRY': 'Turkish Lira - TL',
        'PLN': 'Polish Zloty - zł',
        'MXN': 'Mexican Peso - MX$',
        'NOK': 'Norwegian Krone - Nkr',
        'DKK': 'Danish Krone - Dkr',
        'BRL': 'Brazilian Real - R$',
        'IDR': 'Indonesian Rupiah - Rp',
        'TWD': 'New Taiwan Dollar - NT$',
        'SAR': 'Saudi Riyal - SR',
        'PKR': 'Pakistani Rupee - PKRs',
        'CZK': 'Czech Koruna - Kč',
        'RUB': 'Russian Ruble - RUB',
        'KES': 'Kenyan Shilling - Ksh',
        'ARS': 'Argentine Peso - AR$',
        'EGP': 'Egyptian Pound - EGP',
        'QAR': 'Qatari Rial - QR',
        'RON': 'Romanian Leu - RON',
        'COP': 'Colombian Peso - CO$',
        'BGN': 'Bulgarian Lev - BGN',
        'MAD': 'Moroccan Dirham - MAD',
        'ISK': 'Icelandic Króna - Ikr',
        'LKR': 'Sri Lankan Rupee - SLRs',
        'GEL': 'Georgian Lari - GEL',
        'UAH': 'Ukrainian Hryvnia - ₴',
        'NGN': 'Nigerian Naira - ₦',
        'BDT': 'Bangladeshi Taka - Tk',
        'MUR': 'Mauritian Rupee - MURs',
        'ALL': 'Albanian Lek - ALL',
        'PEN': 'Peruvian Sol - S/.',
        'BOB': 'Bolivian Boliviano - Bs',
        'UYU': 'Uruguayan Peso - $U',
        'BAM': 'Bosnia-Herzegovina Convertible Mark - KM',
        'UZS': 'Uzbekistani Som - UZS',
        'KZT': 'Kazakhstani Tenge - KZT',
        'MKD': 'Macedonian Denar - MKD',
        'MDL': 'Moldovan Leu - MDL',
        'AMD': 'Armenian Dram - AMD',
        'DOP': 'Dominican Peso - RD$',
        'JMD': 'Jamaican Dollar - J$',
        'DZD': 'Algerian Dinar - DA',
        'CRC': 'Costa Rican Colón - ₡',
        'BND': 'Brunei Dollar - BN$',
        'TTD': 'Trinidad & Tobago Dollar - TT$',
        'LBP': 'Lebanese Pound - LB£',
        'KHR': 'Cambodian Riel - KHR',
        'NPR': 'Nepalese Rupee - NPRs'
    } as { [key: string]: string },
    
    destinationMap: {
        'THA': 'Thailand',
        'BR': 'Brazil',
    } as { [key: string]: string },

    destinationSelector: 'Search destination'
}